[package]
name = "pixel-sig"
version = "0.1.0"
authors = ["lovesh <lovesh.bond@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
#error-chain = "0.11.0"
failure = "0.1.5"

[dependencies.amcl_wrapper]
version = "0.1.6"
#path = "../amcl_wrapper/"
default-features = false
features = ["bls381"]

[dependencies.clear_on_drop]
version = "0.2.3"
